### ISSUE TITLE
Wont Connect 

### ISSUE THREAD

**Issue by gdotp01** [msteitz/homebridge-octoprint-connect#1]
Hi,
Ive installed this plugin and no matter what I do it does not seem to connect. The IP address and API key are correct.

**Comment by msteitz** [comment]
Hi,
Please check a few things:
1. Octoprint Web Interface is reachable from homebridge 
2. In Octoprint settings CORS is enabled (Settings->API)
3. Your 3D-Printer is online and sending temperature data to Octoprint (wont see a connection if the 3D-Printer is offline)
4. In the plugin settings in homebridge you specified the full URL of Octoprint, e.g. http://192.168.0.5:5000/
5. Double check your API key
6. If you are using application keys check the permissions. Maybe use the global API key for testing

**Comment by gdotp01** [comment]
Hi. Thanks for getting back.
Cors was not enabled but it is now and that appears to have done the trick

**Comment by msteitz** [comment]
Happy to help!

**Comment by Notyly** [comment]
Hi msteitz, 

I have also problem. 

Used your checklist from above:
1) Don't know how to do this. My homebridge is running on docker / Synology NAS
2) Check
3) Check
4) Check
5) Check
6) Check

It shows the icon in Homekit, but temperature is always 0

Could you please help me?

Thanks,
Patrick

**Comment by msteitz** [comment]
Hi Patrick,

Item 1 on the checklist is there to assure a working network connection between your Homebridge and your Octoprint instance. This is to make sure, there are no firewalls etc. blocking the traffic. 

I uploaded version 1.1.4. This gives you the ability to enable debug mode for your printer through the Homebridge UI plugin settings. Please activate, restart your Homebridge and check the log for the output once you open HomeKit (or the devices screen in the Homebridge UI). Should give you an error message.

Regards

**Comment by Notyly** [comment]
OK,

it seems that is the case:
<img width="738" alt="Bildschirmfoto 2021-01-22 um 21 54 42" src="https://user-images.githubusercontent.com/77847659/105545794-c6b1ff00-5cfc-11eb-88bf-fa0d84d5964c.png">
What can I do? I am using FritzBox. There is no active firewall... DO I have to make port forwarding?

**Comment by msteitz** [comment]
Hmm, I can reproduce that error if I enter a wrong API key, wrong port or disable CORS in Octoprint settings. Can you please double check these settings (even if it sounds silly...). If you are not doing it already use the global API key from Octoprint for testing to make sure there is no issue with permissions on Octoprint side.

I have set up a Homebridge on an older synology NAS to connect to an octoprint running on a RasPi for testing, also with a FritzBox for routing. As long as all are in the same network everything was running fine without any port forwarding.
