### ISSUE TITLE
I would like see temperatures in Celsius 

### ISSUE THREAD

**Issue by BengalPrint** [msteitz/homebridge-octoprint-connect#2]
Is it possible to have an option Celsius ?

**Comment by msteitz** [comment]
Hi,
If it is Celsius or Fahrenheit is depending on your Home.app and general system setup. Octoprint just reports a number and the „TemperatureSensor“ Service that the plugin is publishing also just sends a number to Homebridge -> HomeKit. I tried if I can have any influence on that through the plugin, but that property is not supported by the „TemperatureSensor“ service, so I can not send a unit for the number.

In my personal setup Octoprint is showing temperature in Celsius and also my Home.app is showing all temperatures in Celsius. Maybe you can check on the settings in your Home.app and Octoprint?

**Comment by msteitz** [comment]
Closed because of inactivity
