### ISSUE TITLE
Can´t reach HomeKit / Gerät antwortet nicht

### ISSUE THREAD

**Issue by funk01** [msteitz/homebridge-octoprint-connect#4]
Hi,

what a great idea to add Octoprint Temperature to HomeKit.

Sadly i don´t get data, but i see the printer in HomeKit. HomeKit reports firmware 1.1.3, but it says it can´t reach the machine.
I tried also octopi.local as IP.
{
    "bridge": {
        "name": "Homebridge",
        "username": "1E:23:52:2B:3C:B7",
        "port": 51849,
        "pin": "712-49-944"
    },
    "accessories": [
        {
            "name": "Anycubic Pro",
            "server": "192.168.178.99",
            "api_key": "62FDD5DDY478467CBFB3YFA85X90332E",
            "accessory": "Octoprint-Temp"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        }
    ]
}

HomeKit says that the plugin is working. No errors. Any idea?

Thanks

(ps: Numbers are fake, but Code is exact.)

**Comment by msteitz** [comment]
Hi,
Thank you for your feedback!
Try entering the full URL including the port of your octoprint instance, e.g. http://192.168.0.10:5000/
Best regards!

**Comment by funk01** [comment]
Solved: I didn´t enter any IP and left field empty. Only Api-Key. Works like a charm! Thx!
